config/routes.rb
Rails.application.routes.draw do
  root 'activities#statistics'
  resources :activities
end

app/models/activity.rb
class Activity < ApplicationRecord
  require 'geocoder'

  validates_presence_of :starting_street,
                        :starting_city,
                        :starting_country, :end_street,
                        :end_city,
                        :end_country
  validate :valid_address, on: %i[create update]

  before_save :set_distance
  def self.group_by_day
    Activity.where(created_at: get_week_range).order(created_at: :desc).group_by { |x| x.created_at.to_date }
  end

  private


  def set_distance
    starting_address = "#{starting_street}, #{starting_city}, #{starting_country}"
    end_address = "#{end_street}, #{end_city}, #{end_country}"

    start_coords = coordinates(starting_address)
    end_coords = coordinates(end_address)
    self.distance = calculate_distance(start_coords, end_coords)

  end

  def calculate_distance(point_1, point_2)
    Geocoder::Calculations.distance_between(point_1, point_2)
  end

  def valid_address
    starting_address = "#{starting_street}, #{starting_city}, #{starting_country}"
    end_address = "#{end_street}, #{end_city}, #{end_country}"

    if !coordinates(starting_address) || !coordinates(end_address)
      errors.add(:base, "Could not find address, please enter valid address")
    end
  end

  def coordinates(address)
    Geocoder.coordinates(address)
  end

  def self.get_week_range
    Date.today.at_beginning_of_week.beginning_of_day..Date.today.at_end_of_week.end_of_day
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: %i[ show edit update destroy]

  def index
    @activities = Activity.all.order(created_at: :desc)
  end

  def show
  end

  def new
    @activity = Activity.new

  end

  def edit
  end

  def create
    @activity = Activity.new(activity_params)

    respond_to do |format|
      if @activity.save
        format.html { redirect_to root_path, notice: "Activity was successfully created." }
        format.json { render :statistics, status: :created, location: @activity }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: "Activity was successfully updated." }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: "Activity was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def statistics
    activities_per_days = Activity.group_by_day
    @activities = []
    activities_per_days.each do |day, activities|
      row = {
        distance: activities.select(&:distance).sum(&:distance),
        created_at: day
      }
      @activities << row
    end
    @activities
  end

  private

  def set_activity
    @activity = Activity.find(params[:id])
  end

  def activity_params
    params.require(:activity).permit(:starting_street,
                                     :starting_city,
                                     :starting_country, :end_street,
                                     :end_city,
                                     :end_country, :created_at)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/activities_helper.rb
module ActivitiesHelper
  def format_distance(number)
    "#{number}km"
  end

  def format_date(date)
    date.strftime("%e\. %B")
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/activities/_form.html.erb
<%= form_with(model: activity, class: "styled-form") do |form| %>
  <% if activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
        <% activity.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<header class="styled-header">
  <p>
    Please provide address in the following format:<br/>
    <span class="text-italic">
      Street name, City, Country
    </span>
  </p>
</header>


  <div class="field">
    <%= form.label :starting_address %>

    <%= form.text_field :starting_street, placeholder: 'Street' %>
    <%= form.text_field :starting_city, placeholder: 'City' %>
    <%= form.text_field :starting_country, placeholder: 'Country' %>

  </div>

  <div class="field">
    <%= form.label :end_address %>

    <%= form.text_field :end_street, placeholder: 'Street' %>
    <%= form.text_field :end_city, placeholder: 'City' %>
    <%= form.text_field :end_country, placeholder: 'Country' %>
  </div>

  <p class="text-italic">
    Optional
  </p>

  <div class="field">
    <%= form.label :activity_date %>
    <%= form.date_field :created_at %>
  </div>

  <div class="actions btn-submit">
    <%= form.submit %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing Activity</h1>

<%= render 'form', activity: @activity %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Activities</h1>

<table class="styled-table">
  <thead>
    <tr>
      <th>Date</th>
      <th>Distance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @activities.each do |activity| %>
      <tr>
        <td><%= format_date(activity.created_at) %></td>
        <td><%= format_distance(activity.distance) %></td>
        <td><%= link_to 'Show', activity %></td>
        <td><%= link_to 'Edit', edit_activity_path(activity) %></td>
        <td><%= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Activity', new_activity_path %>
<%= link_to 'Statistics', root_path %>

app/views/activities/new.html.erb
<h1>New Activity</h1>

<%= render 'form', activity: @activity %>

<%= link_to 'Back', root_path %>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Distance:</strong>
  <%= @activity.distance %>
</p>

<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>

app/views/activities/statistics.html.erb
<p id="notice"><%= notice %></p>

<h1>Statistics</h1>
<h3>Activities added this week</h3>

<table class="styled-table">
  <thead>
    <tr>
      <th>Date</th>
      <th>Distance</th>
    </tr>
  </thead>

  <tbody>
  <%if @activities.empty? %>
    <tr>
      <td>-</td>
      <td>-</td>
    </tr>
  <% end %>
    <% @activities.each do |activity| %>
      <tr>
        <td><%= format_date(activity[:created_at]) %></td>
        <td><%= format_distance(activity[:distance]) %></td>
      </tr>
    <% end %>

  </tbody>
</table>

<br>

<%= link_to 'New Activity', new_activity_path %>
<%= link_to 'Show all Activities', activities_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fitofit</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>